# Majority Vote Baseline Configuration
# For detailed parameter descriptions, see selection/README.md

verifier_cfg:
  verifier_type: "all" # Options: "reward_models", "judges", "all"
  verifier_size: "all" # Options: "all", "small", "medium", "large", or integer
  verifier_subset: [] # Optional: specific verifier names to use

data_cfg:
  dataset_name: "MMLU-Pro" # Options: "MATH-500", "MMLU-Pro", "MMLU", "GPQA", "GPQA-Diamond", "GPQA-1K"
  train_split: 1.0 # 1.0 = no test set, <1.0 = fraction for training
  train_queries: 1 # Fraction or number of training queries to use
  train_samples: 1 # Fraction of samples per problem to use
  nan_replacement: 0 # Replace NaN with: 0 or "mean"
  random_seed: 0
  model_size: "70B" # For dataset selection: "8B" or "70B"
  reward_threshold: null # Binarization threshold, null = no threshold
  save_weaver_scores: false # Save Weaver scores as column in local dataset
  
  # Score normalization (not used for majority vote)
  normalize_type: "per_problem" # Options: "per_problem", "all_problems"
  normalize_method: "minmax" # Options: "minmax", "quantile", "winsorize"
  normalize_params: ${normalize_method_params.${data_cfg.normalize_method}}
  
  # Problem similarity (not used for majority vote)
  closest_train_problem_method: "mean_verifier_distance"
  closest_train_problem_metric_type: "euclidean"
  
  verifier_cfg: ${verifier_cfg}
  mv_as_verifier: false # Don't include majority vote as verifier
  fixed_test_split: null
  same_train_test: null

debug: false

model_cfg:
  model_type: "majority_vote" # Options: "majority_vote", "coverage"
  model_class: "per_dataset" # Options: "per_problem", "per_dataset"
  model_params: ${model_params.${model_cfg.model_type}}

fit_cfg:
  fit_type: null # Not used for majority vote

logging: null # Options: "wandb", null
wandb_cfg:
  project: "verification"
  entity: "${oc.env:WANDB_ENTITY}"

# Model-specific parameters
model_params:
  majority_vote:
    k: 1 # Check if answer is positive in top k majority responses
    majority_select: "one_sample" # Options: "majority", "one_sample"
    
  coverage:
    tmp: # No parameters required
    
  first_sample:
    tmp: # No parameters required
    
  naive_ensemble:
    tmp: # No parameters required

# Normalization method parameters (not used for majority vote)
normalize_method_params:
  minmax:
    tmp: # No parameters required
    
  quantile:
    output_distribution: "uniform"
    n_quantiles: 100
    
  winsorize:
    lower_quantile: 0.05
    upper_quantile: 0.95